FROM rust:latest as builder
WORKDIR /app
COPY . .
RUN cargo build --release --package build-controller --bin deployer

FROM debian:latest
WORKDIR /app
COPY --from=builder /app/target/release/deployer .

CMD ["./deployer"]
