FROM rust:latest as builder
WORKDIR /app
COPY . .
RUN cargo build --release --package nix-serve-service

FROM debian:latest
WORKDIR /app
RUN mkdir -p /app/nar && \
    chown 1069:1069 /app/nar

COPY --from=builder /app/target/release/nix-serve-service .

USER 1069
CMD ["./nix-serve-service"]
