FROM rust:latest as builder
WORKDIR /app
COPY . .
RUN cargo build --release --package build-controller --bin jobs-list-ui --workspace

FROM debian:latest
WORKDIR /app
COPY --from=builder /app/target/release/jobs-list-ui .

CMD ["./jobs-list-ui"]
