FROM rust:latest as builder
WORKDIR /app
COPY . .
RUN cargo build --release --package build-controller --bin job-ui

FROM debian:latest
WORKDIR /app
COPY --from=builder /app/target/release/job-ui .

CMD ["./job-ui"]
