apiVersion: batch/v1
kind: Job
metadata:
  name: nix-build-job
  namespace: nixbuilder
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
      - name: nix-builder
        image: nixos/nix
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
        command:
        - /bin/sh
        - -c
        - |
          git clone https://github.com/myorg/myrepo && \
          cd myrepo && \
          nix build .#docker
      restartPolicy: Never
