apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nix-build-controller
  namespace: default
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - build.example.com
    resources:
      - nixbuilds
      - nixbuilds/status
    verbs:
      - get
      - list
      - watch
      - update
      - create
      - patch
