apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: buildjobs.builds.example.com
spec:
  group: builds.example.com
  names:
    kind: BuildJob
    plural: buildjobs
    singular: buildjob
    shortNames:
    - bj
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required: ["repository"]
            properties:
              repository:
                type: string
              branch:
                type: string
                default: "main"
              flakeTarget:
                type: string
                default: ".#docker"
              resources:
                type: object
                properties:
                  memory:
                    type: string
                  cpu:
                    type: string
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Succeeded", "Failed"]
              startTime:
                type: string
                format: date-time
              completionTime:
                type: string
                format: date-time
