apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nixbuilds.build.example.com
spec:
  group: build.example.com
  names:
    kind: NixBuild
    plural: nixbuilds
    singular: nixbuild
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["git_repo", "image_name"]
              properties:
                git_repo:
                  type: string
                git_ref:
                  type: string
                nix_attr:
                  type: string
                image_name:
                  type: string
